"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import {
  buildAuctionCaption,
  buildPollPlan,
  buildPollTitle,
  cardConditions,
  cardLanguages,
  DEFAULT_POLL_OPTIONS,
  MAX_POLL_OPTIONS,
} from "@/lib/auction-wizard";
import { uploadCardImageBatch } from "@/lib/card-image";
import { createPublicSupabaseClient } from "@/lib/supabase";

type Group = { id:string; name:string; is_default:boolean };
type FormState = { name:string; collection:string; cardNumber:string; variant:string; condition:string; language:string; imageUrl:string; lotNumber:string; startingPrice:string; increment:string; buyout:string; optionCount:string; endAt:string; publication:"now"|"scheduled"; scheduledAt:string; groupId:string };
type PublishProgress = { auction:{id:string;lotNumber:number;status:string}; card:{name:string;hasImage:boolean}; group:{name:string}; dispatch:{status:string;announcementSent:boolean;pollSent:boolean;sentAt:string|null;attempts:number;lastError:string|null}; bot:{online:boolean;connected:boolean;status:string;workerId:string|null} };
type Created = { auctionId:string; lot:number; name:string; publication:"now"|"scheduled"; scheduledAt:string };

const localInput=(date:Date)=>{const off=date.getTimezoneOffset()*60000;return new Date(date.getTime()-off).toISOString().slice(0,16)};
const money=(value:number|null)=>value==null||!Number.isFinite(value)?"—":new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value);
const initial=():FormState=>({name:"",collection:"",cardNumber:"",variant:"Normal",condition:cardConditions[0],language:"pt-BR",imageUrl:"",lotNumber:"",startingPrice:"1",increment:"1",buyout:"",optionCount:String(DEFAULT_POLL_OPTIONS),endAt:localInput(new Date(Date.now()+65*60_000)),publication:"now",scheduledAt:localInput(new Date(Date.now()+5*60_000)),groupId:""});
const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));

export default function NewAuctionWizard(){
  const router=useRouter(); const [db]=useState(createPublicSupabaseClient); const [ready,setReady]=useState(false); const [session,setSession]=useState<any>(null);
  const [groups,setGroups]=useState<Group[]>([]); const [step,setStep]=useState(1); const [form,setForm]=useState<FormState>(initial); const [imageFile,setImageFile]=useState<File|null>(null); const [previewUrl,setPreviewUrl]=useState(""); const [imageProgress,setImageProgress]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [created,setCreated]=useState<Created|null>(null); const [progress,setProgress]=useState<PublishProgress|null>(null); const [watching,setWatching]=useState(false); const [showAdvanced,setShowAdvanced]=useState(false);
  async function authFetch(url:string,init?:RequestInit){const {data}=await db.auth.getSession();if(!data.session)throw new Error("Entre novamente no painel.");return fetch(url,{...init,cache:"no-store",headers:{...init?.headers,Authorization:`Bearer ${data.session.access_token}`}})}
  useEffect(()=>{void(async()=>{const {data}=await db.auth.getSession();setSession(data.session);setReady(true);if(!data.session)return;const r=await authFetch("/api/auctions/new");const b=await r.json();if(!r.ok)throw new Error(b.error??"Não foi possível preparar o leilão.");setGroups(b.groups??[]);setForm(f=>({...f,lotNumber:String(b.suggestedLotNumber??""),groupId:b.defaultGroupId??b.groups?.[0]?.id??""}))})().catch(e=>setError(e instanceof Error?e.message:"Falha ao carregar."))},[db]);
  useEffect(()=>{if(!imageFile){setPreviewUrl("");return}const url=URL.createObjectURL(imageFile);setPreviewUrl(url);return()=>URL.revokeObjectURL(url)},[imageFile]);
  const start=Number(form.startingPrice), increment=Number(form.increment), buyout=form.buyout.trim()?Number(form.buyout):null, optionCount=Number(form.optionCount||DEFAULT_POLL_OPTIONS);
  const plan=useMemo(()=>buildPollPlan(start,increment,buyout,optionCount),[start,increment,buyout,optionCount]); const options=plan.options; const group=groups.find(g=>g.id===form.groupId); const image=previewUrl||form.imageUrl;
  const caption=buildAuctionCaption({lotNumber:form.lotNumber||"?",name:form.name||"Carta",cardNumber:form.cardNumber,condition:form.condition,language:form.language}); const pollTitle=buildPollTitle(form.lotNumber||"?");
  const overflowMessage=plan.overflow&&buyout!=null&&plan.minimumIncrement!=null?`Esses valores gerariam ${plan.optionCount} opções, mas o limite é ${MAX_POLL_OPTIONS}. Use incremento de pelo menos ${money(plan.minimumIncrement)}.`:plan.overflow?`A enquete aceita no máximo ${MAX_POLL_OPTIONS} opções.`:"";
  const patch=<K extends keyof FormState>(key:K,value:FormState[K])=>setForm(f=>({...f,[key]:value}));
  function validate(target:number){setError("");if(target>=2&&!form.name.trim()){setError("Informe o nome da carta.");return false}if(target>=2&&form.imageUrl&&!/^https:\/\//i.test(form.imageUrl)){setError("A URL da imagem precisa começar com HTTPS.");return false}if(target>=3){if(!Number.isFinite(start)||start<0){setError("Lance inicial inválido.");return false}if(!Number.isFinite(increment)||increment<=0){setError("Incremento inválido.");return false}if(buyout!=null&&(!Number.isFinite(buyout)||buyout<=start)){setError("O ARREMATE deve ser maior que o lance inicial.");return false}if(buyout==null&&(!Number.isSafeInteger(optionCount)||optionCount<2||optionCount>MAX_POLL_OPTIONS)){setError(`Escolha entre 2 e ${MAX_POLL_OPTIONS} opções.`);return false}if(overflowMessage){setError(overflowMessage);return false}if(!form.groupId){setError("Selecione o grupo do WhatsApp.");return false}if(!options.length||options.length>MAX_POLL_OPTIONS){setError("Não foi possível montar a enquete.");return false}const pub=form.publication==="now"?Date.now():new Date(form.scheduledAt).getTime();if(form.publication==="scheduled"&&!Number.isFinite(pub)){setError("Horário de publicação inválido.");return false}if(form.endAt&&new Date(form.endAt).getTime()<=pub){setError("O encerramento deve ser depois da publicação.");return false}}return true}
  function next(){if(validate(step+1))setStep(s=>Math.min(4,s+1))}
  async function upload(){
    if(!imageFile)return form.imageUrl.trim()||null;
    const {uploaded,failures}=await uploadCardImageBatch({client:db,authFetch,items:[{id:"single",file:imageFile}],onStatus:(_id,_stage,message)=>setImageProgress(message??"")});
    const result=uploaded.get("single");if(!result?.url)throw new Error(failures[0]?.message??"Falha no upload da imagem.");
    patch("imageUrl",result.url);setImageFile(null);setImageProgress(result.deduplicated?"Imagem reutilizada, sem novo armazenamento.":result.optimized?`Imagem otimizada para ${Math.round(result.sizeBytes/1024)} KB.`:"Imagem enviada sem recompressão desnecessária.");return result.url;
  }
  async function watchPublication(auctionId:string){setWatching(true);try{for(let i=0;i<20;i++){const r=await authFetch(`/api/auctions/new/status?auctionId=${encodeURIComponent(auctionId)}`);const b=await r.json();if(!r.ok)throw new Error(b.error??"Não foi possível acompanhar o envio.");setProgress(b);if(b.dispatch?.status==="sent"&&b.auction?.status==="open")break;if(!b.bot?.online||b.dispatch?.status==="failed")break;await wait(1000)}}catch(e){setError(e instanceof Error?e.message:"Falha ao acompanhar o envio.")}finally{setWatching(false)}}
  async function publish(){if(!validate(4))return;setBusy(true);setError("");try{const imageUrl=await upload();const scheduledAt=form.publication==="now"?new Date().toISOString():new Date(form.scheduledAt).toISOString();const r=await authFetch("/api/auctions/new",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({eventId:crypto.randomUUID(),card:{name:form.name,collection:form.collection,card_number:form.cardNumber,variant:form.variant,condition:form.condition,language:form.language,image_url:imageUrl},auction:{lot_number:form.lotNumber?Number(form.lotNumber):null,starting_price:start,bid_increment:increment,buyout_price:buyout,option_count:optionCount,scheduled_at:scheduledAt,scheduled_end_at:form.endAt?new Date(form.endAt).toISOString():null,group_id:form.groupId}})});const b=await r.json();if(!r.ok)throw new Error(b.error??"Não foi possível criar o leilão.");const auctionId=String(b.data?.auction?.id??"");const nextCreated={auctionId,lot:Number(b.data?.auction?.lot_number??form.lotNumber),name:form.name,publication:form.publication,scheduledAt};setCreated(nextCreated);setBusy(false);if(form.publication==="now"&&auctionId)void watchPublication(auctionId)}catch(e){setError(e instanceof Error?e.message:"Falha ao publicar.");setBusy(false)}}
  if(!ready)return <main className="shell"><p>Carregando…</p></main>;
  if(!session)return <main className="shell"><section className="panel"><h1>Novo leilão</h1><p className="muted">Entre primeiro no painel.</p><Link href="/">Voltar</Link></section></main>;
  if(created){const done=progress?.dispatch.status==="sent"&&progress?.auction.status==="open";const offline=progress&&!progress.bot.online;return <main className="shell"><section className="panel wizard-success"><p className="eyebrow">PUBLICAÇÃO</p><h1>Lote #{created.lot} · {created.name}</h1><div className="publish-progress"><p>✅ Lote #{created.lot} salvo</p>{created.publication==="scheduled"?<p>🕒 Envio agendado para {new Date(created.scheduledAt).toLocaleString("pt-BR")}</p>:<>{!progress&&watching&&<p>⏳ Aguardando o bot…</p>}{offline&&<><p>🔴 Bot offline</p><p className="muted">O dispatch continua salvo e será retomado automaticamente quando o bot voltar.</p></>}{progress&&!offline&&<><p>{progress.dispatch.announcementSent?"✅":"⏳"} {progress.card.hasImage?"Imagem enviada":"Anúncio enviado"}</p><p>{progress.dispatch.pollSent?"✅":"⏳"} Enquete enviada</p><p>{progress.auction.status==="open"?"✅":"⏳"} Leilão aberto</p></>}{progress?.dispatch.status==="failed"&&<p className="alert">Falha no envio: {progress.dispatch.lastError??"o bot tentará conforme a política de retry."}</p>}{done&&<p className="notice">Tudo certo. O leilão já está ao vivo no WhatsApp e no painel.</p>}</>}</div><div className="actions"><button onClick={()=>router.push("/")}>Voltar ao painel</button><button onClick={()=>router.push("/whatsapp")}>Central WhatsApp</button></div></section></main>}
  return <main className="shell wizard-shell">
    <header className="topbar"><div><p className="eyebrow">NOVO LEILÃO</p><h1>Criar leilão</h1><p className="muted">Carta → valores → prévia → publicar.</p></div><Link href="/">← Cancelar</Link></header>
    <nav className="wizard-steps">{["Carta","Valores","Prévia","Publicar"].map((x,i)=><button key={x} type="button" className={step===i+1?"active":step>i+1?"done":""} onClick={()=>i+1<step&&setStep(i+1)}>{i+1}. {x}</button>)}</nav>
    {error&&<p className="alert" role="alert">{error}</p>}
    {step===1&&<section className="panel wizard-card"><div><p className="eyebrow">ETAPA 1</p><h2>Carta</h2><p className="muted">093/198 é o número da carta dentro da coleção, não o lote.</p></div><div className="wizard-form-two"><div className="form-grid"><label>Nome<input value={form.name} onChange={e=>patch("name",e.target.value)} placeholder="Kubfu" autoFocus /></label><label>Coleção / Edição<input value={form.collection} onChange={e=>patch("collection",e.target.value)} /></label><label>Número da carta<input value={form.cardNumber} onChange={e=>patch("cardNumber",e.target.value)} placeholder="093/198" /></label><label>Variante<input value={form.variant} onChange={e=>patch("variant",e.target.value)} /></label><label>Condição<select value={form.condition} onChange={e=>patch("condition",e.target.value)}>{cardConditions.map(x=><option key={x}>{x}</option>)}</select></label><label>Idioma<select value={form.language} onChange={e=>patch("language",e.target.value)}>{cardLanguages.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label></div><div className="form-grid"><label>Upload da imagem<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{setImageProgress("");setImageFile(e.target.files?.[0]??null)}} /></label><div className="or-divider">ou</div><label>URL HTTPS<input type="url" value={form.imageUrl} disabled={!!imageFile} onChange={e=>patch("imageUrl",e.target.value)} placeholder="https://..." /></label><div className="wizard-image-preview">{image?<img src={image} alt="Prévia da carta"/>:<span>Imagem da carta</span>}</div>{imageProgress&&<small>{imageProgress}</small>}</div></div></section>}
    {step===2&&<section className="panel wizard-card"><div><p className="eyebrow">ETAPA 2</p><h2>Valores e publicação</h2><p className="muted">A enquete é gerada automaticamente a partir do lance inicial, incremento e ARREMATE.</p></div><div className="wizard-form-two"><div className="form-grid"><label>Número do lote<input type="number" min="1" step="1" value={form.lotNumber} onChange={e=>patch("lotNumber",e.target.value)}/></label><label>Lance inicial<input type="number" min="0" step="0.01" value={form.startingPrice} onChange={e=>patch("startingPrice",e.target.value)}/></label><label>Incremento<input type="number" min="0.01" step="0.01" value={form.increment} onChange={e=>patch("increment",e.target.value)}/></label><label>ARREMATE (opcional)<input type="number" min="0" step="0.01" value={form.buyout} onChange={e=>patch("buyout",e.target.value)}/></label>{buyout==null&&<div className="wizard-more"><button type="button" className="secondary" onClick={()=>setShowAdvanced(v=>!v)}>{showAdvanced?"Ocultar opções":"Mais opções"}</button>{showAdvanced&&<label>Quantidade de opções<input type="number" min="2" max={MAX_POLL_OPTIONS} step="1" value={form.optionCount} onChange={e=>patch("optionCount",e.target.value)}/><small>Sem ARREMATE, o padrão é {DEFAULT_POLL_OPTIONS} opções.</small></label>}</div>}<label>Encerramento<input type="datetime-local" value={form.endAt} onChange={e=>patch("endAt",e.target.value)}/></label></div><div className="form-grid"><fieldset className="wizard-fieldset"><legend>Publicação</legend><label className="radio-row"><input type="radio" checked={form.publication==="now"} onChange={()=>patch("publication","now")}/> Agora</label><label className="radio-row"><input type="radio" checked={form.publication==="scheduled"} onChange={()=>patch("publication","scheduled")}/> Agendada</label></fieldset>{form.publication==="scheduled"&&<label>Data e horário<input type="datetime-local" value={form.scheduledAt} onChange={e=>patch("scheduledAt",e.target.value)}/></label>}<label>Grupo<select value={form.groupId} onChange={e=>patch("groupId",e.target.value)}><option value="">Selecione…</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>{!groups.length&&<p className="alert">Nenhum grupo sincronizado. Atualize os grupos na Central WhatsApp.</p>}{overflowMessage?<p className="alert">{overflowMessage}</p>:<div className="bid-box compact-bid"><span>Enquete gerada</span><strong>{options.length} opções</strong><div className="poll-chip-list">{options.map(o=><span key={`${o.amount}-${o.isBuyout}`}>{o.label}</span>)}</div></div>}</div></div></section>}
    {step===3&&<section className="panel wizard-card"><p className="eyebrow">ETAPA 3</p><h2>Prévia do WhatsApp</h2><p className="muted">Imagem + legenda curta + enquete nativa, com uma opção ativa por pessoa.</p><div className="whatsapp-preview"><div className="wa-chat"><div className="wa-media-message">{image?<img src={image} alt={form.name}/>:<div className="wa-no-image">Sem imagem</div>}<p>{caption}</p></div><div className="wa-poll"><strong>{pollTitle}</strong><small>Selecione uma opção</small>{options.map(o=><div key={`${o.amount}-${o.isBuyout}`} className={o.isBuyout?"buyout":""}><span className="wa-radio">○</span><span>{o.label}</span></div>)}</div></div><aside className="preview-details"><div><span>Grupo</span><strong>{group?.name??"Sem grupo"}</strong></div><div><span>Lance inicial</span><strong>{money(start)}</strong></div><div><span>Incremento</span><strong>{money(increment)}</strong></div><div><span>ARREMATE</span><strong>{money(buyout)}</strong></div></aside></div></section>}
    {step===4&&<section className="panel wizard-card"><p className="eyebrow">ETAPA 4</p><h2>{form.publication==="now"?"Publicar agora":"Agendar publicação"}</h2><p className="muted">Uma confirmação salva carta, lote, opções e dispatch de forma atômica.</p><div className="publish-summary"><div><span>Lote</span><strong>{form.lotNumber}. {form.name}</strong></div><div><span>Grupo</span><strong>{group?.name??"—"}</strong></div><div><span>Publicação</span><strong>{form.publication==="now"?"Agora":new Date(form.scheduledAt).toLocaleString("pt-BR")}</strong></div><div><span>Encerramento</span><strong>{form.endAt?new Date(form.endAt).toLocaleString("pt-BR"):"Manual"}</strong></div></div><div className="poll-chip-list">{options.map(o=><span key={`${o.amount}-${o.isBuyout}`}>{o.label}</span>)}</div>{imageProgress&&<p className="notice">Imagem: {imageProgress}</p>}<p className="notice">Se o bot estiver offline, o lote continua salvo e o dispatch fica pendente até o worker voltar.</p></section>}
    <div className="wizard-actions"><button type="button" disabled={busy||step===1} onClick={()=>setStep(s=>Math.max(1,s-1))}>← Voltar</button>{step<4?<button type="button" disabled={busy} onClick={next}>Continuar →</button>:<button type="button" disabled={busy||!groups.length} onClick={()=>void publish()}>{busy?"Salvando…":form.publication==="now"?"PUBLICAR AGORA":"AGENDAR PUBLICAÇÃO"}</button>}</div>
  </main>;
}
